# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('any', 'Any'), ('meat', 'Meat'), ('veg', 'Vegetable')], default='any', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('any', 'Any'), ('meat', 'Meat'), ('veg', 'Vegetable')], default='any', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ToppingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('homogenous', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='topping',
            name='topping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.ToppingType'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.ToppingType'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizza_shop.Topping'),
        ),
    ]
