# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 13:47
from __future__ import unicode_literals

from django.core import management
from django.db import migrations

def load_quick_demo(apps, schema_editor):
    management.call_command('loaddata', 'quick_demo.json')

class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_quick_demo)
    ]
