# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0002_quick_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='type',
            new_name='pizza_type_char',
        ),
    ]
