# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0003_auto_20180316_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppingtype',
            name='universal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='toppingtype',
            name='homogenous',
            field=models.BooleanField(default=False),
        ),
    ]
