# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='multiselect',
            field=models.CharField(choices=[(1, 'Item 1'), (2, 'Item 2'), (3, 'Item 3')], default='', max_length=100),
        ),
    ]
