# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_multiselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='multiselect',
            field=models.CharField(choices=[('Item 1', 'Item 1'), ('Item 2', 'Item 2'), ('Item 3', 'Item 3')], default='', max_length=100),
        ),
    ]
