# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20171116_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='multiselect',
            field=models.CharField(choices=[('CA', 'California'), ('OR', 'Oregon'), ('WA', 'Washington'), (0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (3.5, 'Three-point-five'), (10, 'Ten'), (True, 'True'), (False, 'False')], default='', max_length=100),
        ),
    ]
