# Generated by Django 2.0.3 on 2018-03-14 13:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20171118_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='mselect',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CA', 'California'), ('OR', 'Oregon'), ('WA', 'Washington'), (0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (3.5, 'Three-point-five'), (10, 'Ten'), (True, 'True'), (False, 'False')], max_length=34, null=True),
        ),
    ]
