# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_multiselectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='mselect',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CA', 'California'), ('OR', 'Oregon'), ('WA', 'Washington'), ('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('3.5', 'Three-point-five'), ('10', 'Ten'), ('True', 'True'), ('False', 'False')], max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='multiselect',
            field=models.CharField(choices=[('CA', 'California'), ('OR', 'Oregon'), ('WA', 'Washington'), ('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('3.5', 'Three-point-five'), ('10', 'Ten'), ('True', 'True'), ('False', 'False')], default='', max_length=100),
        ),
    ]
